### PR TITLE
Test coverage & refactor

### PR DESCRIPTION
**Pull request by msanroman**
- Tested endpoints and API-common methods (parseBody, GET & POST) with
  mocha.
- Applied the single responsibility principle the best I could, now:
  - buffer-api knows which endpoint call for each of its public methods.
  - Each endpoint knows which url must hit, and if it is a POST or a GET
    request.
  - api.coffee handles the response parsing and callback handling, and
    knows how to parameterize GET and POST requests.
- Added sample.coffee file, which shows a little example of API usage.

### CODE REVIEW

**Comment by msanroman** [comment]
Hey @colinscape!

I'd love to know your thoughts & @nieldlr's too about this pull request :)

I know both of you are super busy but I'm really looking forward to have a chat about these changes  :grin:

**Comment by nieldlr** [comment]
Hi @msanroman,

terribly sorry for the slow reply here. This is looking really great. I enjoy the abstraction + the tests. I think, if @colinscape thinks it's good too we can definitely merge this in. We're actually thinking of making this repo an official node wrapper for the Buffer API. :)

**Comment by msanroman** [comment]
Wow, awesome @nieldlr!

Thanks for your response (and no reason to be sorry at all!) :)

**Comment by colinscape** [comment]
Thanks so much for the work, and the nudge, @msanroman :smiley: 

I've merged it all in and then added some of the additional dev dependencies. Great work!

**Comment by msanroman** [comment]
Thanks for the merge @colinscape :smile: :tada: !

Also, thanks for adding the additional dependencies, didn't realized that was missing.

You guys rock! :)

**Pull request merged**
